name: Solidity unit test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install node modules
        run: yarn install
      - name: Unit test hardhat
        run: |
          npx hardhat node &
          npx hardhat test
